namespace Crews.Web.Cipher.Html;

public class AElement : HtmlElement { public AElement() : base("a") { } }
public class AbbrElement : HtmlElement { public AbbrElement() : base("abbr") { } }
public class AddressElement : HtmlElement { public AddressElement() : base("address") { } }
public class AreaElement : HtmlElement { public AreaElement() : base("area") { } }
public class ArticleElement : HtmlElement { public ArticleElement() : base("article") { } }
public class AsideElement : HtmlElement { public AsideElement() : base("aside") { } }
public class AudioElement : HtmlElement { public AudioElement() : base("audio") { } }
public class BElement : HtmlElement { public BElement() : base("b") { } }
public class BaseElement : HtmlElement { public BaseElement() : base("base") { } }
public class BdoElement : HtmlElement { public BdoElement() : base("bdo") { } }
public class BlockquoteElement : HtmlElement { public BlockquoteElement() : base("blockquote") { } }
public class BodyElement : HtmlElement { public BodyElement() : base("body") { } }
public class BrElement : HtmlElement { public BrElement() : base("br") { } }
public class ButtonElement : HtmlElement { public ButtonElement() : base("button") { } }
public class CanvasElement : HtmlElement { public CanvasElement() : base("canvas") { } }
public class CaptionElement : HtmlElement { public CaptionElement() : base("caption") { } }
public class CiteElement : HtmlElement { public CiteElement() : base("cite") { } }
public class CodeElement : HtmlElement { public CodeElement() : base("code") { } }
public class ColElement : HtmlElement { public ColElement() : base("col") { } }
public class ColgroupElement : HtmlElement { public ColgroupElement() : base("colgroup") { } }
public class CommandElement : HtmlElement { public CommandElement() : base("command") { } }
public class DatalistElement : HtmlElement { public DatalistElement() : base("datalist") { } }
public class DdElement : HtmlElement { public DdElement() : base("dd") { } }
public class DelElement : HtmlElement { public DelElement() : base("del") { } }
public class DetailsElement : HtmlElement { public DetailsElement() : base("details") { } }
public class DfnElement : HtmlElement { public DfnElement() : base("dfn") { } }
public class DivElement : HtmlElement { public DivElement() : base("div") { } }
public class DlElement : HtmlElement { public DlElement() : base("dl") { } }
public class DtElement : HtmlElement { public DtElement() : base("dt") { } }
public class EmElement : HtmlElement { public EmElement() : base("em") { } }
public class EmbedElement : HtmlElement { public EmbedElement() : base("embed") { } }
public class FieldsetElement : HtmlElement { public FieldsetElement() : base("fieldset") { } }
public class FigcaptionElement : HtmlElement { public FigcaptionElement() : base("figcaption") { } }
public class FigureElement : HtmlElement { public FigureElement() : base("figure") { } }
public class FooterElement : HtmlElement { public FooterElement() : base("footer") { } }
public class FormElement : HtmlElement { public FormElement() : base("form") { } }
public class H1Element : HtmlElement { public H1Element() : base("h1") { } }
public class H2Element : HtmlElement { public H2Element() : base("h2") { } }
public class H3Element : HtmlElement { public H3Element() : base("h3") { } }
public class H4Element : HtmlElement { public H4Element() : base("h4") { } }
public class H5Element : HtmlElement { public H5Element() : base("h5") { } }
public class H6Element : HtmlElement { public H6Element() : base("h6") { } }
public class HeadElement : HtmlElement { public HeadElement() : base("head") { } }
public class HeaderElement : HtmlElement { public HeaderElement() : base("header") { } }
public class HrElement : HtmlElement { public HrElement() : base("hr") { } }
public class IElement : HtmlElement { public IElement() : base("i") { } }
public class IframeElement : HtmlElement { public IframeElement() : base("iframe") { } }
public class ImgElement : HtmlElement { public ImgElement() : base("img") { } }
public class InputElement : HtmlElement { public InputElement() : base("input") { } }
public class InsElement : HtmlElement { public InsElement() : base("ins") { } }
public class KbdElement : HtmlElement { public KbdElement() : base("kbd") { } }
public class LabelElement : HtmlElement { public LabelElement() : base("label") { } }
public class LegendElement : HtmlElement { public LegendElement() : base("legend") { } }
public class LiElement : HtmlElement { public LiElement() : base("li") { } }
public class LinkElement : HtmlElement { public LinkElement() : base("link") { } }
public class MapElement : HtmlElement { public MapElement() : base("map") { } }
public class MarkElement : HtmlElement { public MarkElement() : base("mark") { } }
public class MenuElement : HtmlElement { public MenuElement() : base("menu") { } }
public class MetaElement : HtmlElement { public MetaElement() : base("meta") { } }
public class MeterElement : HtmlElement { public MeterElement() : base("meter") { } }
public class NavElement : HtmlElement { public NavElement() : base("nav") { } }
public class NoscriptElement : HtmlElement { public NoscriptElement() : base("noscript") { } }
public class ObjectElement : HtmlElement { public ObjectElement() : base("object") { } }
public class OlElement : HtmlElement { public OlElement() : base("ol") { } }
public class OptgroupElement : HtmlElement { public OptgroupElement() : base("optgroup") { } }
public class OptionElement : HtmlElement { public OptionElement() : base("option") { } }
public class OutputElement : HtmlElement { public OutputElement() : base("output") { } }
public class PElement : HtmlElement { public PElement() : base("p") { } }
public class ParamElement : HtmlElement { public ParamElement() : base("param") { } }
public class PreElement : HtmlElement { public PreElement() : base("pre") { } }
public class ProgressElement : HtmlElement { public ProgressElement() : base("progress") { } }
public class QElement : HtmlElement { public QElement() : base("q") { } }
public class RpElement : HtmlElement { public RpElement() : base("rp") { } }
public class RtElement : HtmlElement { public RtElement() : base("rt") { } }
public class RubyElement : HtmlElement { public RubyElement() : base("ruby") { } }
public class SElement : HtmlElement { public SElement() : base("s") { } }
public class SampElement : HtmlElement { public SampElement() : base("samp") { } }
public class ScriptElement : HtmlElement { public ScriptElement() : base("script") { } }
public class SectionElement : HtmlElement { public SectionElement() : base("section") { } }
public class SelectElement : HtmlElement { public SelectElement() : base("select") { } }
public class SmallElement : HtmlElement { public SmallElement() : base("small") { } }
public class SourceElement : HtmlElement { public SourceElement() : base("source") { } }
public class SpanElement : HtmlElement { public SpanElement() : base("span") { } }
public class StrongElement : HtmlElement { public StrongElement() : base("strong") { } }
public class StyleElement : HtmlElement { public StyleElement() : base("style") { } }
public class SubElement : HtmlElement { public SubElement() : base("sub") { } }
public class SupElement : HtmlElement { public SupElement() : base("sup") { } }
public class TableElement : HtmlElement { public TableElement() : base("table") { } }
public class TbodyElement : HtmlElement { public TbodyElement() : base("tbody") { } }
public class TdElement : HtmlElement { public TdElement() : base("td") { } }
public class TextareaElement : HtmlElement { public TextareaElement() : base("textarea") { } }
public class TfootElement : HtmlElement { public TfootElement() : base("tfoot") { } }
public class ThElement : HtmlElement { public ThElement() : base("th") { } }
public class TheadElement : HtmlElement { public TheadElement() : base("thead") { } }
public class TimeElement : HtmlElement { public TimeElement() : base("time") { } }
public class TitleElement : HtmlElement { public TitleElement() : base("title") { } }
public class TrElement : HtmlElement { public TrElement() : base("tr") { } }
public class TrackElement : HtmlElement { public TrackElement() : base("track") { } }
public class UElement : HtmlElement { public UElement() : base("u") { } }
public class UlElement : HtmlElement { public UlElement() : base("ul") { } }
public class VarElement : HtmlElement { public VarElement() : base("var") { } }
public class VideoElement : HtmlElement { public VideoElement() : base("video") { } }
public class WbrElement : HtmlElement { public WbrElement() : base("wbr") { } }